apiVersion: apps/v1
kind: Deployment
metadata:
  name: harpy
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: harpy
  template:
    metadata:
      labels:
        app: harpy
    spec:
      containers:
      - image: tf7a/harpy:20241128231903202411282317592024112823154020241128230924latest
        name: harpy
