name: Python application
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  
    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: tf7a/harpy
            
    - name: Clone Repo
      run: |
        git config user.name "DictateurBienveillant"
        git config user.email "cedric.trottier@monboreal.ca"
        git config user.password ${{ secrets.TOKEN_FORGIT }}
        gh repo clone PotatEnjoyerOfTomboys/Harpy
        git pull
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_FORGIT }}            

    - name: Build and push Docker image
      id: build-image
      run: |
        IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)
        IMAGE_NAME="tf7a/harpy:$IMAGE_TAG"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV # Store image tag for use in next steps

    - name: Modify YAML using sed
      run: |
            cd guestbook
            ls
            sed -i 's|image: tf7a/harpy:.*|image: tf7a/harpy:${{ env.IMAGE_TAG }}|' deployment.yaml
            echo ${{ env.IMAGE_TAG }}
  
    - name: Commit and push changes
      run: |
            git config user.name "DictateurBienveillant"
            git config user.email "cedric.trottier@monboreal.ca"
            git config user.password ${{ secrets.TOKEN_FORGIT }}
            git add guestbook/deployment.yaml
            git commit -m "Update YAML file using sed"
            git push -u origin main
      env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_FORGIT }}

